[package]
name = "rust-auth"
version = "1.0.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
oauth2 = "4.4.2"
tokio = { version = "1.37.0", features = ["full"] }
rand = "0.8.5"
rocket = "0.5.0"
redis = { version = "0.25.3", features = ["tls-native-tls"] }
serde_json = "1.0.116"